# Generated by Django 4.1.1 on 2022-11-08 06:58

import app_premises.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayHouseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty_name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('realty_country', models.CharField(default='Россия', max_length=250, verbose_name='Страна')),
                ('realty_region', models.CharField(default='Московская область', max_length=250, verbose_name='Регион')),
                ('realty_city', models.CharField(default='Москва', max_length=250, verbose_name='Населенный пункт')),
                ('realty_address', models.CharField(help_text='Улица, дом, корпус...', max_length=250, verbose_name='Адрес')),
                ('realty_to_city', models.CharField(blank=True, max_length=10, verbose_name='Расстояние до города')),
                ('realty_type', models.CharField(choices=[('h', 'Отель'), ('c', 'Хостел'), ('a', 'Апартаменты'), ('ah', 'Апарт-отель'), ('gh', 'Гостевой дом'), ('k', 'Коттедж'), ('v', 'Вилла'), ('kp', 'Кемпинг'), ('gp', 'Глэмпинг')], max_length=2, verbose_name='Тип объекта')),
                ('full_description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('realty_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('is_advertised', models.BooleanField(default=False, verbose_name='Статус продвижения')),
                ('slug', models.SlugField(default=None, unique=True, verbose_name='URL')),
                ('count_of_persons', models.PositiveIntegerField(default=1, verbose_name='Количество спальных мест')),
                ('realty_area', models.PositiveIntegerField(blank=True, verbose_name='Площадь')),
                ('book_cancel', models.CharField(choices=[('y', 'Беспл. отмена брони'), ('n', 'Нет беспл. отмены брони')], default='n', max_length=1, verbose_name='Отмена бронирования')),
                ('pay_type', models.CharField(choices=[('o', 'Оплата онлайн'), ('c', 'Оплата на месте')], default='o', max_length=1, verbose_name='Способ оплаты')),
                ('food_options', models.CharField(choices=[('a', 'Завтрак включён'), ('b', 'Завтрак + обед или ужин включены'), ('c', 'Завтрак, обед и ужин включены'), ('d', 'Всё включено'), ('e', 'Питание не включено')], default='e', max_length=1, verbose_name='Опции питания')),
                ('arriving_time', models.TimeField(default='14:00', verbose_name='Время заселения')),
                ('departure_time', models.TimeField(default='12:00', verbose_name='Время выезда')),
                ('realty_book_count', models.PositiveIntegerField(default=0, verbose_name='Бронирований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app_companies.companyprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'db_table': 'holiday_house_db',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Гатегория')),
                ('icon_url', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'db_table': 'options_db',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_identifier', models.CharField(default=uuid.uuid4, max_length=10, unique=True, verbose_name='Номер бронирования')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выселения')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Бронь')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Гости')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_premises.holidayhouseobject', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'reservation_db',
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=app_premises.models.user_directory_path, validators=[app_premises.models.max_value, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], 'Поддерживаются файлы JPG, JPEG и PNG')], verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата загрузки')),
                ('realty_obj', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_premises.holidayhouseobject', verbose_name='Идентификатор объекта')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'db.photo',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='holidayhouseobject',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='option_list', to='app_premises.realtyoptions', verbose_name='Опции'),
        ),
    ]
