# Generated by Django 4.1.1 on 2023-08-28 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_premises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='camp',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='option_list', to='app_premises.realtyoptions', verbose_name='Опции'),
        ),
        migrations.AddField(
            model_name='camp',
            name='views_count',
            field=models.ManyToManyField(blank=True, to='app_data.ip'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='camps',
            field=models.ManyToManyField(blank=True, related_name='favorite_camps', to='app_premises.camp', verbose_name='Избранные кемпинги'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='favorite_flats', to='app_premises.flat', verbose_name='Избранные квартиры'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='flat',
            name='furniture',
            field=models.ManyToManyField(blank=True, related_name='furnitures', to='app_premises.furnituremodel', verbose_name='Мебель'),
        ),
        migrations.AddField(
            model_name='flat',
            name='technique',
            field=models.ManyToManyField(blank=True, related_name='techniques', to='app_premises.techniquemodel', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='flat',
            name='views_count',
            field=models.ManyToManyField(blank=True, to='app_data.ip'),
        ),
        migrations.AddField(
            model_name='photos',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_photos', to='app_premises.camp', verbose_name='Идентификатор кемпа'),
        ),
        migrations.AddField(
            model_name='photos',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_photos', to='app_premises.flat', verbose_name='Идентификатор квартиры'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Гости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='realty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_premises.camp', verbose_name='Объект недвижимости'),
            preserve_default=False,
        ),
    ]
