# Generated by Django 4.1.1 on 2022-11-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0001_initial'),
        ('app_premises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayhouseobject',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hh_companies', to='app_companies.companyprofile', verbose_name='Пользователь'),
        ),
    ]
