# Generated by Django 4.1.1 on 2022-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='hotel_objects',
        ),
        migrations.AddField(
            model_name='favorite',
            name='camps',
            field=models.ManyToManyField(blank=True, related_name='favorite_camps', to='app_premises.camp', verbose_name='Избранные кемпинги'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='favorite_flats', to='app_premises.flat', verbose_name='Избранные квартиры'),
        ),
    ]
