# Generated by Django 4.1.1 on 2022-11-03 12:26

import app_premises.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0001_initial'),
        ('app_premises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(blank=True, upload_to=app_premises.models.user_directory_path, validators=[app_premises.models.max_value, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], 'Поддерживаются файлы JPG, JPEG и PNG')], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='realtyobject',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app_companies.companyprofile', verbose_name='Пользователь'),
        ),
    ]
