# Generated by Django 4.1.1 on 2022-11-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0002_remove_favorite_hotel_objects_favorite_camps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='flat',
        ),
        migrations.AlterField(
            model_name='realtyoptions',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='photos',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_photos', to='app_premises.camp', verbose_name='Идентификатор кемпа'),
        ),
        migrations.AddField(
            model_name='photos',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_photos', to='app_premises.flat', verbose_name='Идентификатор квартиры'),
        ),
    ]
