# Generated by Django 4.1.1 on 2022-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0002_alter_holidayhouseobject_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayhouseobject',
            name='realty_type',
            field=models.CharField(choices=[('h', 'Отель'), ('c', 'Хостел'), ('a', 'Апартаменты'), ('ah', 'Апарт-отель'), ('gh', 'Гостевой дом'), ('k', 'Коттедж'), ('v', 'Вилла'), ('kp', 'Кемпинг'), ('gp', 'Глэмпинг'), ('kv', 'Квартира'), ('dm', 'Дом')], max_length=2, verbose_name='Тип объекта'),
        ),
    ]
