# Generated by Django 4.1.1 on 2022-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0003_alter_photos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00+0800', verbose_name='Дата бронирования'),
            preserve_default=False,
        ),
    ]
