# Generated by Django 4.1.1 on 2022-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0003_remove_photos_camp_remove_photos_flat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'ordering': ['created_at'], 'verbose_name': 'Кемпинг', 'verbose_name_plural': 'Кемпинги'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['created_at'], 'verbose_name': 'Длительный срок', 'verbose_name_plural': 'Длительный срок'},
        ),
        migrations.AddField(
            model_name='camp',
            name='ind',
            field=models.CharField(blank=True, max_length=6, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='flat',
            name='ind',
            field=models.CharField(blank=True, max_length=6, verbose_name='Индекс'),
        ),
    ]
