# Generated by Django 4.1.1 on 2022-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0003_alter_holidayhouseobject_realty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayhouseobject',
            name='realty_address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='holidayhouseobject',
            name='realty_country',
            field=models.CharField(choices=[('rus', 'Россия')], default='rus', max_length=250, verbose_name='Страна'),
        ),
    ]
