# Generated by Django 4.1.1 on 2022-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0004_alter_camp_options_alter_flat_options_camp_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='stars',
            field=models.CharField(blank=True, choices=[('0', 'Нет звезд'), ('1', '1 звезда'), ('2', '2 звезды'), ('3', '3 звезды'), ('4', '4 звезды'), ('5', '5 звезд')], max_length=1, verbose_name='Звёздность'),
        ),
    ]
