# Generated by Django 4.1.1 on 2022-11-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0004_reservation_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='created_at',
            new_name='booked_at',
        ),
    ]
