# Generated by Django 4.1.1 on 2022-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0004_alter_holidayhouseobject_realty_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayhouseobject',
            name='realty_country',
            field=models.CharField(default='Россия', max_length=250, verbose_name='Страна'),
        ),
    ]
