# Generated by Django 4.1.1 on 2022-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0005_alter_holidayhouseobject_realty_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayhouseobject',
            name='region_center',
            field=models.CharField(blank=True, max_length=30, verbose_name='Региональный центр'),
        ),
    ]
