# Generated by Django 4.1.1 on 2022-12-04 14:00

import app_premises.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_premises', '0005_camp_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='stars',
            field=models.CharField(choices=[('0', 'Нет звезд'), ('1', '1 звезда'), ('2', '2 звезды'), ('3', '3 звезды'), ('4', '4 звезды'), ('5', '5 звезд')], default='0', max_length=1, verbose_name='Звёздность'),
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=app_premises.models.user_directory_path, validators=[app_premises.models.max_value, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], 'Поддерживаются файлы JPG, JPEG и PNG')], verbose_name='Фотография')),
                ('text', models.TextField(max_length=400, verbose_name='Рекламное объявление')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'db_table': 'advertising_db',
                'ordering': ['created_at'],
            },
        ),
    ]
