# Generated by Django 4.1.1 on 2022-11-05 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0005_rename_created_at_reservation_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 11, 3, 50, 673298), verbose_name='Дата бронирования'),
        ),
    ]
