# Generated by Django 4.1.1 on 2022-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0006_alter_reservation_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования'),
        ),
    ]
