# Generated by Django 4.1.1 on 2022-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0006_holidayhouseobject_region_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayhouseobject',
            name='is_favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='holidayhouseobject',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='canceled_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата бронирования'),
        ),
    ]
