# Generated by Django 4.1.1 on 2022-12-06 15:38

import app_premises.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0006_alter_camp_stars_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyoptions',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Искали раз'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(blank=True, upload_to=app_premises.models.advertising_path, validators=[app_premises.models.max_value, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], 'Поддерживаются файлы JPG, JPEG и PNG')], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='text',
            field=models.TextField(blank=True, max_length=400, verbose_name='Рекламное объявление'),
        ),
    ]
