# Generated by Django 4.1.1 on 2022-11-07 09:48
from uuid import uuid4

import app_premises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0007_alter_reservation_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyobject',
            name='is_advertised',
            field=models.BooleanField(default=False, verbose_name='Статус продвижения'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_identifier',
            field=models.CharField(default=uuid4, max_length=10, verbose_name='Номер бронирования'),
        ),
    ]
