# Generated by Django 4.1.1 on 2022-11-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_ip'),
        ('app_premises', '0007_holidayhouseobject_is_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayhouseobject',
            name='views_count',
        ),
        migrations.AddField(
            model_name='holidayhouseobject',
            name='views_count',
            field=models.ManyToManyField(blank=True, related_name='realty_views', to='app_data.ip'),
        ),
    ]
