# Generated by Django 4.1.1 on 2022-12-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0007_realtyoptions_views_count_alter_advertising_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtyoptions',
            options={'ordering': ['views_count'], 'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
    ]
