# Generated by Django 4.1.1 on 2022-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0008_alter_realtyoptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtyoptions',
            options={'ordering': ['-views_count'], 'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AddField(
            model_name='camp',
            name='arriving_time_to',
            field=models.TimeField(default='23:00', verbose_name='Время заселения до'),
        ),
        migrations.AddField(
            model_name='camp',
            name='departure_time_to',
            field=models.TimeField(default='12:00', verbose_name='Время выезда до'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='arriving_time',
            field=models.TimeField(default='14:00', verbose_name='Время заселения с'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='departure_time',
            field=models.TimeField(default='09:00', verbose_name='Время выезда с'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='realty_type',
            field=models.CharField(blank=True, choices=[('k', 'Коттедж'), ('kp', 'Кемпинг'), ('gp', 'Глэмпинг'), ('dm', 'Дом')], max_length=2, verbose_name='Тип объекта'),
        ),
    ]
