# Generated by Django 4.1.1 on 2022-11-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0008_remove_holidayhouseobject_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayhouseobject',
            name='is_favorites',
        ),
    ]
