# Generated by Django 4.1.1 on 2022-11-07 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0008_realtyobject_is_advertised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book_identifier',
            field=models.CharField(default=uuid.uuid4, max_length=10, verbose_name='Номер бронирования'),
        ),
    ]
