# Generated by Django 4.1.1 on 2022-11-07 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0009_alter_reservation_book_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book_identifier',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True, verbose_name='Номер бронирования'),
        ),
    ]
