# Generated by Django 4.1.1 on 2022-12-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0009_alter_realtyoptions_options_camp_arriving_time_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['created_at'], 'verbose_name': 'Объект на длительный срок', 'verbose_name_plural': 'Объекты на длительный срок'},
        ),
    ]
