# Generated by Django 4.1.1 on 2022-11-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0009_remove_holidayhouseobject_is_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменённая'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='canceled_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отмены'),
        ),
    ]
