# Generated by Django 4.1.1 on 2022-11-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermRentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty_name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('realty_country', models.CharField(default='Россия', max_length=250, verbose_name='Страна')),
                ('realty_region', models.CharField(default='Московская область', max_length=250, verbose_name='Регион')),
                ('realty_city', models.CharField(default='Москва', max_length=250, verbose_name='Населенный пункт')),
                ('realty_address', models.CharField(help_text='Улица, дом, корпус...', max_length=250, verbose_name='Адрес')),
                ('realty_to_city', models.CharField(blank=True, max_length=10, verbose_name='Расстояние до города')),
                ('realty_type', models.CharField(choices=[('h', 'Отель'), ('c', 'Хостел'), ('a', 'Апартаменты'), ('ah', 'Апарт-отель'), ('gh', 'Гостевой дом'), ('k', 'Коттедж'), ('v', 'Вилла'), ('kp', 'Кемпинг'), ('gp', 'Глэмпинг')], max_length=2, verbose_name='Тип объекта')),
                ('full_description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('realty_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('is_advertised', models.BooleanField(default=False, verbose_name='Статус продвижения')),
                ('rooms_count', models.PositiveIntegerField(default=1, verbose_name='Количество комнат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lt_companies', to='app_companies.companyprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жильё',
                'verbose_name_plural': 'Жильё',
                'db_table': 'long_term_rent_db',
                'ordering': ['created_at'],
            },
        ),
    ]
