# Generated by Django 4.1.1 on 2022-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0002_remove_longtermrentobject_realty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermrentobject',
            name='district',
            field=models.CharField(choices=[('1', 'Южный')], default='1', max_length=1, verbose_name='Федеральный округ'),
        ),
        migrations.AlterField(
            model_name='longtermrentobject',
            name='realty_address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='longtermrentobject',
            name='realty_country',
            field=models.CharField(choices=[('rus', 'Россия')], default='rus', max_length=250, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='longtermrentobject',
            name='realty_type',
            field=models.CharField(choices=[('a', 'Апартаменты'), ('k', 'Коттедж'), ('v', 'Вилла'), ('kv', 'Квартира'), ('dm', 'Дом')], max_length=2, verbose_name='Тип объекта'),
        ),
    ]
