# Generated by Django 4.1.1 on 2022-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0004_alter_longtermrentobject_realty_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermrentobject',
            name='district',
            field=models.CharField(max_length=10, verbose_name='Федеральный округ'),
        ),
    ]
