# Generated by Django 4.1.1 on 2022-11-09 06:23

import app_ltrent.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0005_alter_longtermrentobject_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermrentobject',
            name='district',
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='animals',
            field=models.BooleanField(blank=True, default=False, verbose_name='Можно с животными'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('a', 'Совмещенный'), ('b', 'Раздельный')], default='a', max_length=1, verbose_name='Санузел'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='children',
            field=models.BooleanField(blank=True, default=False, verbose_name='Можно с детьми'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='city_area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Район города'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Залог'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='floor_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='house_korpus',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Корпус, литер, блок'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='house_number',
            field=models.CharField(default='', max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='micro_city_area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Микрорайон города'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='realty_area',
            field=models.FloatField(blank=True, default=35, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='smoke',
            field=models.BooleanField(blank=True, default=False, verbose_name='Можно курить'),
        ),
        migrations.CreateModel(
            name='LongTermPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=app_ltrent.models.user_directory_path, validators=[app_ltrent.models.max_value, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], 'Поддерживаются файлы JPG, JPEG и PNG')], verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата загрузки')),
                ('long_term_obj', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_ltrent.longtermrentobject', verbose_name='Идентификатор объекта')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'long_term_photo_db',
                'ordering': ['created_at'],
            },
        ),
    ]
