# Generated by Django 4.1.1 on 2022-11-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0006_remove_longtermrentobject_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermrentobject',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='longtermrentobject',
            name='floor_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='longtermrentobject',
            name='realty_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
    ]
