# Generated by Django 4.1.1 on 2022-11-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0007_alter_longtermrentobject_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermrentobject',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус объявления'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
