# Generated by Django 4.1.1 on 2022-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0008_longtermrentobject_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('category', models.CharField(max_length=40, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('category', models.CharField(max_length=40, verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='furniture',
            field=models.ManyToManyField(blank=True, related_name='furnitures', to='app_ltrent.furnituremodel', verbose_name='Мебель'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='technique',
            field=models.ManyToManyField(blank=True, related_name='techniques', to='app_ltrent.techniquemodel', verbose_name='Техника'),
        ),
    ]
