# Generated by Django 4.1.1 on 2022-11-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0009_furnituremodel_techniquemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furnituremodel',
            options={'ordering': ['name'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AlterModelOptions(
            name='techniquemodel',
            options={'ordering': ['name'], 'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelTable(
            name='furnituremodel',
            table='furniture_db',
        ),
        migrations.AlterModelTable(
            name='techniquemodel',
            table='technique_db',
        ),
    ]
