# Generated by Django 4.1.1 on 2022-11-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0010_alter_furnituremodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furnituremodel',
            options={'ordering': ['category'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AlterModelOptions(
            name='techniquemodel',
            options={'ordering': ['category'], 'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='techniquemodel',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Иконка'),
        ),
    ]
