# Generated by Django 4.1.1 on 2022-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0011_alter_furnituremodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermrentobject',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='longtermrentobject',
            name='realty_type',
            field=models.CharField(choices=[('kv', '1-к комнатная квартира'), ('2k', '2-х комнатная квартира'), ('3k', '3-х комнатная квартира'), ('4k', '4-х комнатная квартира'), ('ks', 'Квартира-студия'), ('a', 'Апартаменты'), ('k', 'Коттедж'), ('v', 'Вилла'), ('dm', 'Дом')], max_length=2, verbose_name='Тип объекта'),
        ),
    ]
