# Generated by Django 4.1.1 on 2022-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_ip'),
        ('app_ltrent', '0012_alter_longtermrentobject_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermrentobject',
            name='is_favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='longtermrentobject',
            name='views_count',
            field=models.ManyToManyField(blank=True, related_name='lt_realty_views', to='app_data.ip'),
        ),
    ]
