# Generated by Django 4.1.1 on 2022-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0013_longtermrentobject_is_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermrentobject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
