# Generated by Django 4.1.1 on 2022-11-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0014_alter_longtermrentobject_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermrentobject',
            name='is_favorites',
        ),
    ]
