# Generated by Django 4.1.1 on 2022-12-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicyModel',
        ),
        migrations.DeleteModel(
            name='RulesModel',
        ),
    ]
