# Generated by Django 4.1.1 on 2022-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rules', '0002_privacypolicymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicymodel',
            name='category',
            field=models.CharField(default='Политика конфиденциальности', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='privacypolicymodel',
            name='sub_category',
            field=models.CharField(max_length=100, verbose_name='Подкатегория'),
        ),
    ]
