# Generated by Django 4.1.1 on 2022-11-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Федеральный округ'),
        ),
        migrations.AlterModelTable(
            name='locationmodel',
            table='location_db',
        ),
    ]
