# Generated by Django 4.1.1 on 2023-08-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_comments', '0001_initial'),
        ('app_premises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_premises.camp', verbose_name='Объект недвижимости'),
        ),
    ]
