# Generated by Django 4.1.1 on 2022-11-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=django.utils.timezone.now, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('type', models.CharField(choices=[('c', 'Юридическое лицо'), ('i', 'Индивидуальный предприниматель'), ('p', 'Самозанятый')], default='c', max_length=1, verbose_name='Форма управления')),
                ('full_company_name', models.CharField(blank=True, max_length=100, verbose_name='Полное наименование')),
                ('short_company_name', models.CharField(blank=True, max_length=100, verbose_name='Сокращенное наименование')),
                ('legal_address', models.CharField(blank=True, max_length=250, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=250, verbose_name='Фактический адрес')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
                ('bank_account', models.CharField(blank=True, max_length=22, verbose_name='Рассчётный счёт')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование банка')),
                ('kor_account', models.CharField(blank=True, max_length=22, verbose_name='Корреспондентский счёт')),
                ('bic', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('director', models.CharField(max_length=50, verbose_name='Руководитель')),
                ('company_phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('company_email', models.CharField(max_length=50, verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Управляющий')),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компаний',
                'db_table': 'company_db',
                'ordering': ['created_at'],
            },
        ),
    ]
