# Generated by Django 4.1.1 on 2022-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, verbose_name='Название для slug'),
        ),
    ]
