# Generated by Django 4.1.1 on 2022-11-01 11:56

import app_profiler.managers
from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Номер телефона', max_length=31)),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Мужской'), ('w', 'Женский')], default='m', max_length=1, verbose_name='Пол')),
                ('book_count', models.PositiveIntegerField(default=0, verbose_name='Бронирований')),
                ('status', models.CharField(choices=[('d', 'Джун'), ('D', 'Джун+'), ('m', 'Мид'), ('M', 'Мид+'), ('s', 'Синьор')], default='d', max_length=1, verbose_name='Статус клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_company', models.BooleanField(default=False, verbose_name='Компания')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Статус Администратора')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'app_profiler_customuser',
                'ordering': ['created_at'],
            },
            managers=[
                ('objects', app_profiler.managers.UserManager()),
            ],
        ),
    ]
