# Generated by Django 4.1.1 on 2022-11-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', help_text='Номер телефона', max_length=12),
        ),
    ]
