# Generated by Django 4.1.1 on 2022-12-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телеграмм'),
        ),
    ]
