# Generated by Django 4.1.1 on 2022-11-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiler', '0003_customuser_nick_alter_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nick',
            new_name='slug',
        ),
    ]
