# Generated by Django 4.1.1 on 2022-11-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ltrent', '0014_alter_longtermrentobject_is_active'),
        ('app_premises', '0010_reservation_is_canceled_and_more'),
        ('app_profiler', '0003_customuser_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_favorite',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_objects', models.ManyToManyField(related_name='favorite_hotels', to='app_premises.holidayhouseobject', verbose_name='Избранные отели')),
                ('long_term_objects', models.ManyToManyField(related_name='favorite_lt_objects', to='app_ltrent.longtermrentobject', verbose_name='Избранное жильё')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранныё',
                'verbose_name_plural': 'Избранные',
                'db_table': 'favorite_list_db',
            },
        ),
    ]
