# Generated by Django 4.1.1 on 2022-11-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiler', '0004_rename_nick_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', help_text='Номер телефона', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Имя для slug'),
        ),
    ]
