# Generated by Django 4.1.1 on 2022-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premises', '0010_reservation_is_canceled_and_more'),
        ('app_ltrent', '0015_remove_longtermrentobject_is_favorites'),
        ('app_profiler', '0004_remove_customuser_is_favorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='hotel_objects',
            field=models.ManyToManyField(blank=True, related_name='favorite_hotels', to='app_premises.holidayhouseobject', verbose_name='Избранные отели'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='long_term_objects',
            field=models.ManyToManyField(blank=True, related_name='favorite_lt_objects', to='app_ltrent.longtermrentobject', verbose_name='Избранное жильё'),
        ),
    ]
